### ISSUE TITLE
CMM2

### ISSUE THREAD

**Issue by Brian151** [tomysshadow/Shockwave-Wrappers#1]
Tried [and failed] to get Candy Mountain Massacre 2 to run in a projector
I have all the files [I think...] , but pretty sure I have the wrong version projector[s] or something

**Comment by tomysshadow** [comment]
Use the Projector here under Cartoon Network > Adult Swim
https://mega.nz/#F!ppJBySSC!LCR6NbqXpUpyXqH_1eemhQ

Or use BlueMaxima's Flashpoint.

**Comment by Brian151** [comment]
i still haven't bothered with flashpoint yet...lol
can't remember why
i think it's that mainly it's not useful/necessary for me atm

well thanks
will check that out when i'm not busy with my other stuff

**Comment by Brian151** [comment]
alright, gave it a try, seems to work
so thanks
